'use client';
import {useEffect,useState} from 'react';
import {signIn,signOut} from 'next-auth/react';
import './admin.css';
import originalLanding from '../../content/original-landing.json';
const tabs=['홈페이지 문구','사용방법·영상','자주 묻는 질문','공지사항','개인정보처리방침','이용약관','연결·연락처','게시 이력'];
function Field({label,value,onChange,rows=1,type='text',hint}){return <label className="field"><span>{label}</span>{rows>1?<textarea rows={rows} value={value} onChange={e=>onChange(e.target.value)}/>:<input type={type} value={value} onChange={e=>onChange(e.target.value)}/>} {hint&&<small>{hint}</small>}</label>;}
export default function Editor({email,enabled}){
  const [state,setState]=useState(null),[tab,setTab]=useState(0),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[message,setMessage]=useState('');
  const content=state?.draft;
  async function load(){try{const r=await fetch('/api/admin/state',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error);setState(d);setDirty(false);}catch(e){setMessage(e.message);}}
  useEffect(()=>{if(email)load();},[email]);
  useEffect(()=>{const fn=e=>{if(dirty){e.preventDefault();e.returnValue='';}};window.addEventListener('beforeunload',fn);return()=>window.removeEventListener('beforeunload',fn);},[dirty]);
  function edit(key,value){setState(s=>({...s,draft:{...s.draft,[key]:value}}));setDirty(true);setMessage('변경한 내용을 초안으로 저장해 주세요.');}
  async function action(name,extra={}){
    setBusy(true);setMessage('처리 중…');
    try{const r=await fetch('/api/admin/'+name,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:state.version,...extra})});const d=await r.json();if(!r.ok)throw Error(d.error);setState(d);setDirty(false);setMessage(name==='publish'?'공개 홈페이지에 반영했습니다.':name==='restore'?'이전 내용을 초안으로 가져왔습니다. 확인 후 게시해 주세요.':'초안을 저장했습니다. 미리보기로 확인해 주세요.');return true;}catch(e){setMessage(e.message);return false;}finally{setBusy(false);}
  }
  async function preview(){if(dirty){setMessage('미리보기 전에 초안을 저장해 주세요.');return;}window.open('/'+(tab===4?'privacy.html':tab===5?'terms.html':tab===1||tab===2?'guide.html':'index.html')+'?preview=draft','_blank','noopener');}
  async function upload(kind,file){if(!file)return;setBusy(true);setMessage('파일을 올리고 있습니다…');try{const r=await fetch('/api/admin/upload',{method:'POST',headers:{'Content-Type':'application/octet-stream','X-Media-Kind':kind},body:file});const d=await r.json();if(!r.ok)throw Error(d.error);edit(kind==='video'?'videoUrl':'videoPoster',d.path);setMessage('파일을 올렸습니다. 초안 저장 → 미리보기 → 공개 반영 순서로 진행해 주세요.');}catch(e){setMessage(e.message);}finally{setBusy(false);}}
  if(!email)return <main className="login"><img src="/assets/brand/icon-192.png" alt="논담 연꽃" width="64" height="64"/><h1>논담 관리자</h1><p>홈페이지 소식과 안내를 관리하는 공간입니다.</p>{enabled?<><button onClick={()=>signIn('google',{callbackUrl:'/admin'})}>Google 계정으로 로그인</button><p className="muted">지정된 관리자만 이용할 수 있습니다.</p></>:<p role="status">관리자 로그인 준비 중입니다. 운영자가 서버 설정을 완료하면 이용할 수 있습니다.</p>}<a href="/">홈페이지로 돌아가기</a></main>;
  return <div className="admin-shell"><header className="admin-head"><a className="brand" href="/" target="_blank" rel="noopener"><img src="/assets/brand/icon-192.png" width="36" height="36" alt=""/>논담 <span>홈페이지 관리</span></a><div><span className="email">{email}</span><button className="quiet" disabled={busy} onClick={()=>{if(!dirty||confirm('저장하지 않은 변경이 있습니다. 로그아웃할까요?'))signOut({callbackUrl:'/admin'});}}>로그아웃</button></div></header>
    <div className="workspace"><nav aria-label="관리 메뉴">{tabs.map((t,i)=><button key={t} aria-current={tab===i?'page':undefined} onClick={()=>setTab(i)}>{t}</button>)}<p>초안은 관리자에게만 보입니다.<br/>‘공개 반영’을 눌러 게시하세요.</p></nav>
    <main className="editor"><div className="title-row"><div><p className="kicker">NONDAM · F-PLAY</p><h1>{tabs[tab]}</h1></div><span className={'badge '+(dirty?'unsaved':'')}>{dirty?'저장 전 변경 있음':'초안 저장됨'}</span></div>
    <div role="status" aria-live="polite" className="status">{message||'내용을 편집한 뒤 초안으로 저장하세요.'}</div>
    {!content?<p>내용을 불러오는 중입니다. <button onClick={load}>다시 불러오기</button></p>:<fieldset disabled={busy}>
      {tab===0&&<><p className="muted">각 항목 위의 최초 문구는 수정 전 원문입니다. 초안 저장·공개 반영·복원 후에도 바뀌지 않습니다. 아래 입력칸에서 문구를 수정하세요. 줄바꿈은 화면에도 반영됩니다.</p>{content.landing.map((b,i)=><section className="landing-field" key={b.id} aria-labelledby={'original-title-'+b.id}><h2 id={'original-title-'+b.id}>문구 {i+1}</h2><p className="original-copy">{originalLanding[b.id]??'최초 문구가 등록되지 않았습니다.'}</p><Field label={`문구 ${i+1} 수정할 문구`} value={b.text} rows={b.tag==='p'?3:2} onChange={v=>edit('landing',content.landing.map((x,j)=>j===i?{...x,text:v}:x))}/></section>)}</>}
      {tab===1&&<><Field label="사용방법 소개" value={content.guideIntro} rows={4} onChange={v=>edit('guideIntro',v)}/><section className="card"><h2>튜토리얼 영상</h2><p>MP4 또는 WebM · 최대 80MB · 자동재생하지 않습니다.</p><input aria-label="영상 업로드" type="file" accept="video/mp4,video/webm" onChange={e=>upload('video',e.target.files[0])}/><p className="path">현재 파일: {content.videoUrl||'없음'}</p>{content.videoUrl&&<button className="quiet" onClick={()=>edit('videoUrl','')}>영상 연결 해제</button>}<h2>재생 전 이미지</h2><input aria-label="포스터 업로드" type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>upload('poster',e.target.files[0])}/><p className="path">현재 이미지: {content.videoPoster||'없음'}</p>{content.videoPoster&&<button className="quiet" onClick={()=>edit('videoPoster','')}>이미지 연결 해제</button>}<Field label="유튜브 보조 링크 (선택)" value={content.youtubeUrl} onChange={v=>edit('youtubeUrl',v)}/></section></>}
      {tab===2&&<>{content.faq.map((f,i)=>{const change=(key,v)=>edit('faq',content.faq.map((x,j)=>i===j?{...x,[key]:v}:x));return <section className="card" key={f.id}><Field label={`질문 ${i+1}`} value={f.question} onChange={v=>change('question',v)}/><Field label="홈페이지에 보일 짧은 답변" value={f.shortAnswer} rows={3} onChange={v=>change('shortAnswer',v)}/><Field label="가이드의 자세한 답변" value={f.fullAnswer} rows={5} onChange={v=>change('fullAnswer',v)}/><label><input type="checkbox" checked={f.onLanding} onChange={e=>change('onLanding',e.target.checked)}/> 소개 홈페이지에도 표시</label><div className="row"><button className="quiet" disabled={!i} onClick={()=>{const a=[...content.faq];[a[i-1],a[i]]=[a[i],a[i-1]];edit('faq',a);}}>위로</button><button className="quiet" disabled={i===content.faq.length-1} onClick={()=>{const a=[...content.faq];[a[i],a[i+1]]=[a[i+1],a[i]];edit('faq',a);}}>아래로</button><button className="danger" onClick={()=>{if(confirm('이 질문을 초안에서 삭제할까요?'))edit('faq',content.faq.filter((_,j)=>j!==i));}}>질문 삭제</button></div></section>})}<button onClick={()=>edit('faq',[...content.faq,{id:'faq-'+crypto.randomUUID(),question:'새 질문',shortAnswer:'',fullAnswer:'',onLanding:false}])}>질문 추가</button></>}
      {tab===3&&<><p className="muted">게시 시작일·종료일은 한국 시간 기준입니다. 날짜를 비우면 기간 제한 없이 표시합니다.</p>{content.notices.map((n,i)=>{const change=(key,v)=>edit('notices',content.notices.map((x,j)=>i===j?{...x,[key]:v}:x));return <section className="card" key={n.id}><Field label="공지 제목" value={n.title} onChange={v=>change('title',v)}/><Field label="공지 내용" rows={7} value={n.body} onChange={v=>change('body',v)}/><div className="row"><Field label="시작일" type="date" value={n.start} onChange={v=>change('start',v)}/><Field label="종료일" type="date" value={n.end} onChange={v=>change('end',v)}/></div><label><input type="checkbox" checked={n.pinned} onChange={e=>change('pinned',e.target.checked)}/> 중요 공지로 상단 표시</label><button className="danger" onClick={()=>{if(confirm('이 공지를 초안에서 삭제할까요?'))edit('notices',content.notices.filter((_,j)=>j!==i));}}>공지 삭제</button></section>})}<button onClick={()=>edit('notices',[...content.notices,{id:crypto.randomUUID(),title:'새 공지',body:'',start:'',end:'',pinned:false}])}>공지 추가</button></>}
      {(tab===4||tab===5)&&(()=>{const key=tab===4?'privacy':'terms';return <><Field label="시행일" type="date" value={content[key].effectiveDate} onChange={v=>edit(key,{...content[key],effectiveDate:v})}/><Field label="전체 내용" rows={26} value={content[key].body} onChange={v=>edit(key,{...content[key],body:v})}/><p className="muted">본문은 일반 텍스트로 저장됩니다. 빈 줄로 문단을 나누세요. 게시한 버전은 게시 이력에서 확인·복원할 수 있습니다.</p></>})()}
      {tab===6&&<><Field label="문의 받을 이메일" type="email" value={content.contactEmail} onChange={v=>edit('contactEmail',v)}/><Field label="논담 플랫폼 주소 (선택)" value={content.platformUrl} onChange={v=>edit('platformUrl',v)} hint="https://로 시작하는 주소. 비워 두면 기존 안내 페이지로 연결됩니다."/><p>방문자 가입과 문의 데이터 저장은 없습니다. 문의는 이메일로 주고받습니다.</p></>}
      {tab===7&&<>{state.history.length===0?<p>아직 게시 이력이 없습니다. 첫 공개 반영부터 기록됩니다.</p>:state.history.map(h=><section className="card" key={h.id}><strong>{new Date(h.at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</strong><p>{h.actor}</p><button className="quiet" onClick={()=>{if(confirm('선택한 버전을 초안으로 가져올까요? 현재 초안은 바뀌며, 공개 홈페이지는 그대로 유지됩니다.'))action('restore',{id:h.id});}}>이 버전을 초안으로 복원</button></section>)}</>}
    </fieldset>}
    <footer className="actions"><button disabled={busy||!content} onClick={()=>action('save',{content})}>초안 저장</button><button className="quiet" disabled={busy||dirty||!content} onClick={preview}>미리보기</button><button className="publish" disabled={busy||dirty||!content} onClick={()=>{if(confirm('저장된 초안을 홈페이지에 공개할까요?'))action('publish');}}>공개 반영</button></footer></main></div></div>;
}
