import { chromium } from 'playwright';
import {spawn} from 'node:child_process';
import {mkdtemp,rm,readFile,mkdir} from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import assert from 'node:assert/strict';
import {encode} from 'next-auth/jwt';
const dir=await mkdtemp(path.join(os.tmpdir(),'nondam-browser-'));
const secret=crypto.randomBytes(40).toString('hex');
const base='http://127.0.0.1:8109';
const env={...process.env,DATA_DIR:dir,NEXTAUTH_URL:base,NEXTAUTH_SECRET:secret,GOOGLE_CLIENT_ID:'test-only',GOOGLE_CLIENT_SECRET:'test-only',ADMIN_EMAILS:'nondam-test@gmail.com',ADMIN_GOOGLE_SUBS:'test-sub'};
const server=spawn(process.execPath,['node_modules/next/dist/bin/next','start','-H','127.0.0.1','-p','8109'],{env,stdio:['ignore','pipe','pipe']});
let logs='';server.stdout.on('data',x=>logs+=x);server.stderr.on('data',x=>logs+=x);
let browser;
try{
  for(let i=0;i<100;i++){try{if((await fetch(base+'/admin')).ok)break;}catch{}await new Promise(r=>setTimeout(r,100));}
  assert.equal((await fetch(base+'/api/admin/state')).status,401);
  assert.equal((await fetch(base+'/api/admin/upload',{method:'POST',body:'bad',headers:{Origin:base}})).status,401);
  assert.equal((await fetch(base+'/guide.html?preview=draft')).status,401);
  assert.equal((await fetch(base+'/.env.local')).status,404);
  assert.equal((await fetch(base+'/content/initial.json')).status,404);
  const tail=await fetch(base+'/assets/video/fplay-tutorial-720p.mp4',{headers:{Range:'bytes=-1024'}});
  assert.equal(tail.status,206);assert.equal((await tail.arrayBuffer()).byteLength,1024);
  const cookie='next-auth.session-token='+await encode({secret,token:{email:'nondam-test@gmail.com',adminSub:'test-sub'},maxAge:3600});
  const get=()=>fetch(base+'/api/admin/state',{headers:{Cookie:cookie}}).then(async r=>{assert.equal(r.status,200);return r.json();});
  let s=await get();
  const post=async(action,body,origin=base)=>fetch(base+'/api/admin/'+action,{method:'POST',headers:{Cookie:cookie,Origin:origin,'Content-Type':'application/json'},body:JSON.stringify(body)});
  assert.equal((await post('save',{version:s.version,content:s.draft},'https://evil.test')).status,403);
  assert.equal((await fetch(base+'/api/admin/upload',{method:'POST',headers:{Cookie:cookie,Origin:base,'X-Media-Kind':'poster'},body:'<svg onload="alert(1)"></svg>'})).status,400);
  const jpg=await readFile('site/assets/images/guide-video-poster.jpg');
  const uploaded=await fetch(base+'/api/admin/upload',{method:'POST',headers:{Cookie:cookie,Origin:base,'X-Media-Kind':'poster'},body:jpg}).then(async r=>{assert.equal(r.status,200);return r.json();});
  assert.equal((await fetch(base+'/'+uploaded.path)).status,401);
  s.draft.guideIntro='보안 검증 초안 <script>alert(1)</script>';s.draft.videoPoster=uploaded.path;
  s.draft.notices=[{id:'test-notice',title:'게시 시험 공지',body:'안전한 공지 내용',start:'',end:'',pinned:true}];
  let r=await post('save',{version:s.version,content:s.draft});assert.equal(r.status,200);s=await r.json();
  assert.ok(!(await fetch(base+'/guide.html').then(r=>r.text())).includes('보안 검증 초안'));
  const preview=await fetch(base+'/guide.html?preview=draft',{headers:{Cookie:cookie}}).then(r=>r.text());assert.ok(preview.includes('&lt;script&gt;'));assert.ok(preview.includes('보안 검증 초안'));
  r=await post('save',{version:0,content:s.draft});assert.equal(r.status,409);
  r=await post('publish',{version:s.version});assert.equal(r.status,200);s=await r.json();
  assert.equal((await fetch(base+'/'+uploaded.path)).status,200);
  assert.ok((await fetch(base+'/').then(r=>r.text())).includes('게시 시험 공지'));
  const revokedCookie='next-auth.session-token='+await encode({secret,token:{email:'not-admin@gmail.com',adminSub:'other'},maxAge:3600});
  assert.equal((await fetch(base+'/api/admin/state',{headers:{Cookie:revokedCookie}})).status,401);
  browser=await chromium.launch({headless:true, ...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
  const context=await browser.newContext();const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base+'/guide.html');await page.locator('video').waitFor();
  const result=await page.locator('video').evaluate(async v=>{await v.play();await new Promise(r=>setTimeout(r,1800));return {time:v.currentTime,error:v.error?.code||null,width:v.videoWidth};});
  assert.ok(result.time>1);assert.equal(result.error,null);assert.equal(result.width,1280);console.log('일반 가이드 실제 영상 재생:',JSON.stringify(result));
  const noJS=await browser.newContext({javaScriptEnabled:false});const p2=await noJS.newPage();await p2.goto(base+'/guide.html');assert.equal(await p2.locator('video').count(),1);assert.ok(await p2.locator('video').isVisible());
  await page.setViewportSize({width:390,height:844});await page.goto(base+'/guide.html');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
  await context.addCookies([{name:'next-auth.session-token',value:cookie.split('=')[1],domain:'127.0.0.1',path:'/',httpOnly:true,sameSite:'Lax'}]);
  await page.setViewportSize({width:1280,height:900});await page.goto(base+'/admin');await page.getByRole('heading',{name:'홈페이지 문구',exact:true}).waitFor();
  await page.getByRole('button',{name:'연결·연락처',exact:true}).click();await page.getByLabel('문의 받을 이메일').fill('contact-updated@example.com');
  await page.getByRole('button',{name:'초안 저장',exact:true}).click();await page.getByRole('status').filter({hasText:'초안을 저장했습니다'}).waitFor();
  await mkdir('test-results',{recursive:true});await page.screenshot({path:'test-results/admin-desktop.png',fullPage:true});
  await page.setViewportSize({width:390,height:844});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await page.screenshot({path:'test-results/admin-mobile.png',fullPage:true});
  assert.deepEqual(errors,[]);console.log('권한·CSRF·초안 비공개·파일검사·게시·충돌·관리자 UI·모바일 검사 통과');
}catch(e){console.error(logs.slice(-5000));throw e;}finally{await browser?.close();server.kill('SIGTERM');await new Promise(r=>server.once('exit',r));await rm(dir,{recursive:true,force:true});}
